// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmaRi90VHtFHdu4UsdhqAL9hPSC7xbeOs',
    appId: '1:302482455055:web:b2fa52bd285a6e7bda817a',
    messagingSenderId: '302482455055',
    projectId: 'sakhi-app-71625',
    authDomain: 'sakhi-app-71625.firebaseapp.com',
    storageBucket: 'sakhi-app-71625.firebasestorage.app',
    measurementId: 'G-Y9WVMD4RY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYeig_FBRfHzEODD8PUyPCl07QSPO5CBY',
    appId: '1:302482455055:android:387496fe2770d9ecda817a',
    messagingSenderId: '302482455055',
    projectId: 'sakhi-app-71625',
    storageBucket: 'sakhi-app-71625.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEmsdmX20QqKyCP2FhH2rRL5ISzJlYU6c',
    appId: '1:302482455055:ios:68759d7796be6a9cda817a',
    messagingSenderId: '302482455055',
    projectId: 'sakhi-app-71625',
    storageBucket: 'sakhi-app-71625.firebasestorage.app',
    iosBundleId: 'com.example.sakhiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEmsdmX20QqKyCP2FhH2rRL5ISzJlYU6c',
    appId: '1:302482455055:ios:68759d7796be6a9cda817a',
    messagingSenderId: '302482455055',
    projectId: 'sakhi-app-71625',
    storageBucket: 'sakhi-app-71625.firebasestorage.app',
    iosBundleId: 'com.example.sakhiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmaRi90VHtFHdu4UsdhqAL9hPSC7xbeOs',
    appId: '1:302482455055:web:fbedd05497216273da817a',
    messagingSenderId: '302482455055',
    projectId: 'sakhi-app-71625',
    authDomain: 'sakhi-app-71625.firebaseapp.com',
    storageBucket: 'sakhi-app-71625.firebasestorage.app',
    measurementId: 'G-YJX0100JZR',
  );
}
